"""Chicago Submarket Registry and Spatial Layer for Urban Signal.

Provides comprehensive neighborhood metadata, camera positioning, investment
metrics, division catalog, and geographic bounding boxes for Chicago, IL.
"""

from typing import Dict, List
from src.spatial.submarkets import BoroughMeta, SubmarketMeta

# Chicago Metro overall bounding box
CHICAGO_METRO_BBOX: Dict[str, float] = {
    "min_lat": 41.64,
    "max_lat": 42.03,
    "min_lng": -87.94,
    "max_lng": -87.52,
}

# 6 Chicago Division Bounding Boxes
CHICAGO_DIVISION_BBOXES: Dict[str, Dict[str, float]] = {
    "CENTRAL_DOWNTOWN": {"min_lat": 41.845, "max_lat": 41.910, "min_lng": -87.670, "max_lng": -87.600},
    "NORTH_SIDE":       {"min_lat": 41.900, "max_lat": 41.970, "min_lng": -87.710, "max_lng": -87.620},
    "NORTHWEST_SIDE":   {"min_lat": 41.880, "max_lat": 41.960, "min_lng": -87.750, "max_lng": -87.660},
    "SOUTH_SIDE":       {"min_lat": 41.740, "max_lat": 41.865, "min_lng": -87.660, "max_lng": -87.570},
    "FAR_NORTH_SIDE":   {"min_lat": 41.960, "max_lat": 42.030, "min_lng": -87.750, "max_lng": -87.640},
    "SOUTHWEST_SIDE":   {"min_lat": 41.780, "max_lat": 41.870, "min_lng": -87.740, "max_lng": -87.640},
}


def is_in_chicago_metro(lat: float, lng: float) -> bool:
    """Check if a coordinate lies within the Chicago Metropolitan bounds."""
    return (
        CHICAGO_METRO_BBOX["min_lat"] <= lat <= CHICAGO_METRO_BBOX["max_lat"]
        and CHICAGO_METRO_BBOX["min_lng"] <= lng <= CHICAGO_METRO_BBOX["max_lng"]
    )


# ---------------------------------------------------------------------------
# Comprehensive Chicago Submarket Registry (35 Submarkets Across 6 Divisions)
# ---------------------------------------------------------------------------

CHICAGO_SUBMARKETS: Dict[str, SubmarketMeta] = {
    # =======================================================================
    # CENTRAL_DOWNTOWN (6 Submarkets)
    # =======================================================================
    "Loop": SubmarketMeta(
        name="Loop",
        borough="CENTRAL_DOWNTOWN",
        lat=41.8819,
        lng=-87.6278,
        zoom=14.5,
        pitch=60.0,
        base_lims=0.89,
        capex=12000000.0,
        permit_vel=58.0,
        shift_ratio=1.55,
        sla=50.0,
        description="Chicago's historic central business district featuring major commercial towers, Millennium Park, and adaptive residential conversions.",
        city_id="chicago",
    ),
    "Fulton Market": SubmarketMeta(
        name="Fulton Market",
        borough="CENTRAL_DOWNTOWN",
        lat=41.8867,
        lng=-87.6536,
        zoom=15.0,
        pitch=55.0,
        base_lims=0.95,
        capex=11000000.0,
        permit_vel=68.0,
        shift_ratio=1.72,
        sla=65.0,
        description="Former meatpacking district transformed into premier tech headquarters, Michelin-starred dining, and luxury mid-rise development.",
        city_id="chicago",
    ),
    "River North": SubmarketMeta(
        name="River North",
        borough="CENTRAL_DOWNTOWN",
        lat=41.8924,
        lng=-87.6341,
        zoom=14.5,
        pitch=50.0,
        base_lims=0.90,
        capex=9500000.0,
        permit_vel=52.0,
        shift_ratio=1.48,
        sla=72.0,
        description="High-density entertainment and design district with prominent art galleries, luxury high-rises, and vibrant nightlife.",
        city_id="chicago",
    ),
    "Streeterville": SubmarketMeta(
        name="Streeterville",
        borough="CENTRAL_DOWNTOWN",
        lat=41.8956,
        lng=-87.6197,
        zoom=14.5,
        pitch=50.0,
        base_lims=0.88,
        capex=9200000.0,
        permit_vel=44.0,
        shift_ratio=1.40,
        sla=48.0,
        description="Lakefront high-rise neighborhood home to Northwestern Memorial Hospital, Magnificent Mile shopping, and Navy Pier.",
        city_id="chicago",
    ),
    "South Loop": SubmarketMeta(
        name="South Loop",
        borough="CENTRAL_DOWNTOWN",
        lat=41.8566,
        lng=-87.6258,
        zoom=14.0,
        pitch=45.0,
        base_lims=0.82,
        capex=7800000.0,
        permit_vel=49.0,
        shift_ratio=1.42,
        sla=45.0,
        description="Cultural campus gateway near Museum Campus with extensive residential high-rise infill and transit connectivity.",
        city_id="chicago",
    ),
    "West Loop": SubmarketMeta(
        name="West Loop",
        borough="CENTRAL_DOWNTOWN",
        lat=41.8825,
        lng=-87.6475,
        zoom=14.5,
        pitch=50.0,
        base_lims=0.92,
        capex=9800000.0,
        permit_vel=60.0,
        shift_ratio=1.62,
        sla=60.0,
        description="Vibrant dining and creative office corridor along Randolph Street with extensive timber loft and high-density residential projects.",
        city_id="chicago",
    ),

    # =======================================================================
    # NORTH_SIDE (6 Submarkets)
    # =======================================================================
    "Lincoln Park": SubmarketMeta(
        name="Lincoln Park",
        borough="NORTH_SIDE",
        lat=41.9214,
        lng=-87.6513,
        zoom=14.0,
        pitch=45.0,
        base_lims=0.87,
        capex=8200000.0,
        permit_vel=38.0,
        shift_ratio=1.30,
        sla=52.0,
        description="Affluent historic lakefront neighborhood with historic rowhouses, DePaul University, and prime retail along Armitage and Halsted.",
        city_id="chicago",
    ),
    "Lakeview": SubmarketMeta(
        name="Lakeview",
        borough="NORTH_SIDE",
        lat=41.9430,
        lng=-87.6534,
        zoom=14.0,
        pitch=45.0,
        base_lims=0.84,
        capex=6800000.0,
        permit_vel=46.0,
        shift_ratio=1.35,
        sla=64.0,
        description="Dense, vibrant North Side community encompassing Wrigleyville and Boystown with high pedestrian activity and entertainment.",
        city_id="chicago",
    ),
    "Old Town": SubmarketMeta(
        name="Old Town",
        borough="NORTH_SIDE",
        lat=41.9077,
        lng=-87.6373,
        zoom=14.5,
        pitch=45.0,
        base_lims=0.85,
        capex=7400000.0,
        permit_vel=36.0,
        shift_ratio=1.32,
        sla=56.0,
        description="Historic Victorian neighborhood known for Wells Street dining, comedy clubs (The Second City), and boutique streetscapes.",
        city_id="chicago",
    ),
    "Roscoe Village": SubmarketMeta(
        name="Roscoe Village",
        borough="NORTH_SIDE",
        lat=41.9427,
        lng=-87.6784,
        zoom=14.0,
        pitch=40.0,
        base_lims=0.80,
        capex=5600000.0,
        permit_vel=34.0,
        shift_ratio=1.25,
        sla=42.0,
        description="'Village in the City' with tree-lined streets, local shops on Roscoe Street, and family-oriented multifamily infill.",
        city_id="chicago",
    ),
    "Lincoln Square": SubmarketMeta(
        name="Lincoln Square",
        borough="NORTH_SIDE",
        lat=41.9686,
        lng=-87.6888,
        zoom=14.0,
        pitch=40.0,
        base_lims=0.79,
        capex=5200000.0,
        permit_vel=33.0,
        shift_ratio=1.24,
        sla=40.0,
        description="German-heritage commercial square with brick-paved pedestrian corridors, independent retailers, and cultural anchors.",
        city_id="chicago",
    ),
    "North Center": SubmarketMeta(
        name="North Center",
        borough="NORTH_SIDE",
        lat=41.9515,
        lng=-87.6825,
        zoom=14.0,
        pitch=40.0,
        base_lims=0.81,
        capex=5900000.0,
        permit_vel=35.0,
        shift_ratio=1.26,
        sla=44.0,
        description="Thriving North Side residential enclave with top-rated school districts, craft breweries, and steady residential redevelopment.",
        city_id="chicago",
    ),

    # =======================================================================
    # NORTHWEST_SIDE (7 Submarkets)
    # =======================================================================
    "Wicker Park": SubmarketMeta(
        name="Wicker Park",
        borough="NORTHWEST_SIDE",
        lat=41.9088,
        lng=-87.6796,
        zoom=14.5,
        pitch=45.0,
        base_lims=0.88,
        capex=7900000.0,
        permit_vel=54.0,
        shift_ratio=1.50,
        sla=75.0,
        description="Creative and commercial corridor centered at Six Corners (Milwaukee/Damen/North) with vibrant nightlife, dining, and boutique retail.",
        city_id="chicago",
    ),
    "Bucktown": SubmarketMeta(
        name="Bucktown",
        borough="NORTHWEST_SIDE",
        lat=41.9178,
        lng=-87.6792,
        zoom=14.5,
        pitch=45.0,
        base_lims=0.86,
        capex=7500000.0,
        permit_vel=48.0,
        shift_ratio=1.44,
        sla=58.0,
        description="Trendy residential and retail district along the Bloomingdale Trail (The 606) with modern residential architectural conversions.",
        city_id="chicago",
    ),
    "Logan Square": SubmarketMeta(
        name="Logan Square",
        borough="NORTHWEST_SIDE",
        lat=41.9288,
        lng=-87.7077,
        zoom=14.0,
        pitch=45.0,
        base_lims=0.85,
        capex=6700000.0,
        permit_vel=59.0,
        shift_ratio=1.58,
        sla=70.0,
        description="Historic boulevard district experiencing rapid transit-oriented development, artisanal cocktail lounges, and culinary renewal.",
        city_id="chicago",
    ),
    "Avondale": SubmarketMeta(
        name="Avondale",
        borough="NORTHWEST_SIDE",
        lat=41.9415,
        lng=-87.7120,
        zoom=14.0,
        pitch=40.0,
        base_lims=0.78,
        capex=5100000.0,
        permit_vel=47.0,
        shift_ratio=1.45,
        sla=48.0,
        description="Industrial-to-creative transition zone along Belmont and Milwaukee avenues with acclaimed dining and craft manufacturing.",
        city_id="chicago",
    ),
    "West Town": SubmarketMeta(
        name="West Town",
        borough="NORTHWEST_SIDE",
        lat=41.8936,
        lng=-87.6862,
        zoom=14.0,
        pitch=40.0,
        base_lims=0.83,
        capex=6400000.0,
        permit_vel=50.0,
        shift_ratio=1.46,
        sla=55.0,
        description="Dynamic mixed-use community along Chicago Avenue featuring design showrooms, independent galleries, and residential conversions.",
        city_id="chicago",
    ),
    "Humboldt Park": SubmarketMeta(
        name="Humboldt Park",
        borough="NORTHWEST_SIDE",
        lat=41.9022,
        lng=-87.7212,
        zoom=14.0,
        pitch=40.0,
        base_lims=0.72,
        capex=4300000.0,
        permit_vel=42.0,
        shift_ratio=1.36,
        sla=38.0,
        description="Cultural hub centered around the 207-acre park and Paseo Boricua with expanding commercial and residential rehabilitation.",
        city_id="chicago",
    ),
    "Ukrainian Village": SubmarketMeta(
        name="Ukrainian Village",
        borough="NORTHWEST_SIDE",
        lat=41.8994,
        lng=-87.6847,
        zoom=14.0,
        pitch=40.0,
        base_lims=0.82,
        capex=6100000.0,
        permit_vel=41.0,
        shift_ratio=1.38,
        sla=46.0,
        description="Historic brick rowhouse and cathedral district with mature tree canopy and active commercial nodes on Chicago Avenue.",
        city_id="chicago",
    ),

    # =======================================================================
    # FAR_NORTH_SIDE (5 Submarkets)
    # =======================================================================
    "Rogers Park": SubmarketMeta(
        name="Rogers Park",
        borough="FAR_NORTH_SIDE",
        lat=42.0094,
        lng=-87.6695,
        zoom=13.5,
        pitch=35.0,
        base_lims=0.69,
        capex=3900000.0,
        permit_vel=31.0,
        shift_ratio=1.20,
        sla=32.0,
        description="Lakefront academic anchor community at Chicago's northern border with Loyola University and diverse multifamily housing.",
        city_id="chicago",
    ),
    "Edgewater": SubmarketMeta(
        name="Edgewater",
        borough="FAR_NORTH_SIDE",
        lat=41.9872,
        lng=-87.6612,
        zoom=14.0,
        pitch=40.0,
        base_lims=0.76,
        capex=4800000.0,
        permit_vel=36.0,
        shift_ratio=1.26,
        sla=37.0,
        description="Scenic shoreline neighborhood featuring high-rise lakefront condos, antique shopping on Broadway, and historic Bryn Mawr.",
        city_id="chicago",
    ),
    "Andersonville": SubmarketMeta(
        name="Andersonville",
        borough="FAR_NORTH_SIDE",
        lat=41.9798,
        lng=-87.6684,
        zoom=14.5,
        pitch=40.0,
        base_lims=0.82,
        capex=5700000.0,
        permit_vel=39.0,
        shift_ratio=1.34,
        sla=49.0,
        description="Historic Swedish-heritage commercial district along Clark Street famous for locally-owned independent businesses and vibrant dining.",
        city_id="chicago",
    ),
    "Uptown": SubmarketMeta(
        name="Uptown",
        borough="FAR_NORTH_SIDE",
        lat=41.9664,
        lng=-87.6564,
        zoom=14.0,
        pitch=45.0,
        base_lims=0.77,
        capex=5300000.0,
        permit_vel=45.0,
        shift_ratio=1.40,
        sla=50.0,
        description="Historic entertainment and theater district anchored by the Riviera, Aragon Ballroom, and major transit infrastructure upgrades.",
        city_id="chicago",
    ),
    "Albany Park": SubmarketMeta(
        name="Albany Park",
        borough="FAR_NORTH_SIDE",
        lat=41.9683,
        lng=-87.7280,
        zoom=13.5,
        pitch=35.0,
        base_lims=0.71,
        capex=4100000.0,
        permit_vel=33.0,
        shift_ratio=1.22,
        sla=31.0,
        description="Multicultural commercial core along Lawrence Avenue with extensive culinary diversity and Brown Line terminus connectivity.",
        city_id="chicago",
    ),

    # =======================================================================
    # SOUTH_SIDE (6 Submarkets)
    # =======================================================================
    "Hyde Park": SubmarketMeta(
        name="Hyde Park",
        borough="SOUTH_SIDE",
        lat=41.7943,
        lng=-87.5907,
        zoom=14.0,
        pitch=45.0,
        base_lims=0.84,
        capex=7200000.0,
        permit_vel=40.0,
        shift_ratio=1.36,
        sla=45.0,
        description="Prestigious academic and institutional hub anchored by the University of Chicago, Museum of Science & Industry, and 53rd St retail.",
        city_id="chicago",
    ),
    "Bronzeville": SubmarketMeta(
        name="Bronzeville",
        borough="SOUTH_SIDE",
        lat=41.8252,
        lng=-87.6186,
        zoom=14.0,
        pitch=40.0,
        base_lims=0.76,
        capex=5800000.0,
        permit_vel=51.0,
        shift_ratio=1.48,
        sla=39.0,
        description="Historic Black Metropolis seeing massive mixed-use revitalization, historic greystone restorations, and Bronzeville Lakefront redevelopment.",
        city_id="chicago",
    ),
    "Kenwood": SubmarketMeta(
        name="Kenwood",
        borough="SOUTH_SIDE",
        lat=41.8095,
        lng=-87.5925,
        zoom=14.0,
        pitch=40.0,
        base_lims=0.80,
        capex=6100000.0,
        permit_vel=32.0,
        shift_ratio=1.28,
        sla=34.0,
        description="Historic residential district featuring grand mansions, leafy boulevards, and proximity to Lake Michigan parkland.",
        city_id="chicago",
    ),
    "Woodlawn": SubmarketMeta(
        name="Woodlawn",
        borough="SOUTH_SIDE",
        lat=41.7801,
        lng=-87.5956,
        zoom=13.5,
        pitch=35.0,
        base_lims=0.70,
        capex=4400000.0,
        permit_vel=38.0,
        shift_ratio=1.35,
        sla=28.0,
        description="South Side community adjacent to Jackson Park and the Obama Presidential Center with accelerating residential investments.",
        city_id="chicago",
    ),
    "Chinatown": SubmarketMeta(
        name="Chinatown",
        borough="SOUTH_SIDE",
        lat=41.8517,
        lng=-87.6322,
        zoom=14.5,
        pitch=45.0,
        base_lims=0.82,
        capex=6500000.0,
        permit_vel=43.0,
        shift_ratio=1.37,
        sla=58.0,
        description="Bustling cultural and gastronomic destination centered on Wentworth and Archer avenues with high commercial density.",
        city_id="chicago",
    ),
    "Bridgeport": SubmarketMeta(
        name="Bridgeport",
        borough="SOUTH_SIDE",
        lat=41.8364,
        lng=-87.6511,
        zoom=14.0,
        pitch=40.0,
        base_lims=0.77,
        capex=5000000.0,
        permit_vel=39.0,
        shift_ratio=1.31,
        sla=42.0,
        description="Historic working-class neighborhood evolving into an arts and culinary corridor with Bridgeport Art Center and Morgan Street retail.",
        city_id="chicago",
    ),

    # =======================================================================
    # SOUTHWEST_SIDE (5 Submarkets)
    # =======================================================================
    "Pilsen": SubmarketMeta(
        name="Pilsen",
        borough="SOUTHWEST_SIDE",
        lat=41.8562,
        lng=-87.6563,
        zoom=14.5,
        pitch=45.0,
        base_lims=0.83,
        capex=6300000.0,
        permit_vel=53.0,
        shift_ratio=1.52,
        sla=62.0,
        description="Vibrant cultural corridor along 18th Street known for historic murals, award-winning culinary scene, and creative adaptive reuse.",
        city_id="chicago",
    ),
    "McKinley Park": SubmarketMeta(
        name="McKinley Park",
        borough="SOUTHWEST_SIDE",
        lat=41.8315,
        lng=-87.6728,
        zoom=14.0,
        pitch=35.0,
        base_lims=0.72,
        capex=4200000.0,
        permit_vel=35.0,
        shift_ratio=1.25,
        sla=30.0,
        description="Centrally located southwest neighborhood with strong park anchor, Orange Line transit access, and industrial-loft conversions.",
        city_id="chicago",
    ),
    "Brighton Park": SubmarketMeta(
        name="Brighton Park",
        borough="SOUTHWEST_SIDE",
        lat=41.8194,
        lng=-87.6990,
        zoom=13.5,
        pitch=35.0,
        base_lims=0.68,
        capex=3800000.0,
        permit_vel=32.0,
        shift_ratio=1.20,
        sla=26.0,
        description="Densely populated commercial district along Archer Avenue with steady neighborhood retail and logistics services.",
        city_id="chicago",
    ),
    "Little Village": SubmarketMeta(
        name="Little Village",
        borough="SOUTHWEST_SIDE",
        lat=41.8458,
        lng=-87.7058,
        zoom=14.0,
        pitch=40.0,
        base_lims=0.75,
        capex=4600000.0,
        permit_vel=44.0,
        shift_ratio=1.33,
        sla=46.0,
        description="'Mexico of the Midwest' featuring 26th Street, one of the highest grossing shopping districts in Chicago, with vibrant street commerce.",
        city_id="chicago",
    ),
    "Back of the Yards": SubmarketMeta(
        name="Back of the Yards",
        borough="SOUTHWEST_SIDE",
        lat=41.8067,
        lng=-87.6678,
        zoom=13.5,
        pitch=35.0,
        base_lims=0.66,
        capex=3600000.0,
        permit_vel=30.0,
        shift_ratio=1.22,
        sla=24.0,
        description="Historic Union Stockyards heritage district undergoing modern sustainable manufacturing, food innovation, and community development.",
        city_id="chicago",
    ),
}


# ---------------------------------------------------------------------------
# Chicago Divisions Catalog
# ---------------------------------------------------------------------------

CHICAGO_DIVISIONS: Dict[str, BoroughMeta] = {
    "CENTRAL_DOWNTOWN": BoroughMeta(
        name="CENTRAL_DOWNTOWN",
        center_lat=41.8819,
        center_lng=-87.6278,
        zoom=13.0,
        bbox=CHICAGO_DIVISION_BBOXES["CENTRAL_DOWNTOWN"],
        submarkets=[k for k, v in CHICAGO_SUBMARKETS.items() if v.borough == "CENTRAL_DOWNTOWN"],
        city_id="chicago",
    ),
    "NORTH_SIDE": BoroughMeta(
        name="NORTH_SIDE",
        center_lat=41.9300,
        center_lng=-87.6500,
        zoom=12.5,
        bbox=CHICAGO_DIVISION_BBOXES["NORTH_SIDE"],
        submarkets=[k for k, v in CHICAGO_SUBMARKETS.items() if v.borough == "NORTH_SIDE"],
        city_id="chicago",
    ),
    "NORTHWEST_SIDE": BoroughMeta(
        name="NORTHWEST_SIDE",
        center_lat=41.9200,
        center_lng=-87.7000,
        zoom=12.5,
        bbox=CHICAGO_DIVISION_BBOXES["NORTHWEST_SIDE"],
        submarkets=[k for k, v in CHICAGO_SUBMARKETS.items() if v.borough == "NORTHWEST_SIDE"],
        city_id="chicago",
    ),
    "SOUTH_SIDE": BoroughMeta(
        name="SOUTH_SIDE",
        center_lat=41.8100,
        center_lng=-87.6100,
        zoom=12.0,
        bbox=CHICAGO_DIVISION_BBOXES["SOUTH_SIDE"],
        submarkets=[k for k, v in CHICAGO_SUBMARKETS.items() if v.borough == "SOUTH_SIDE"],
        city_id="chicago",
    ),
    "FAR_NORTH_SIDE": BoroughMeta(
        name="FAR_NORTH_SIDE",
        center_lat=41.9850,
        center_lng=-87.6700,
        zoom=12.5,
        bbox=CHICAGO_DIVISION_BBOXES["FAR_NORTH_SIDE"],
        submarkets=[k for k, v in CHICAGO_SUBMARKETS.items() if v.borough == "FAR_NORTH_SIDE"],
        city_id="chicago",
    ),
    "SOUTHWEST_SIDE": BoroughMeta(
        name="SOUTHWEST_SIDE",
        center_lat=41.8350,
        center_lng=-87.6900,
        zoom=12.0,
        bbox=CHICAGO_DIVISION_BBOXES["SOUTHWEST_SIDE"],
        submarkets=[k for k, v in CHICAGO_SUBMARKETS.items() if v.borough == "SOUTHWEST_SIDE"],
        city_id="chicago",
    ),
}
