"""Minneapolis, Minnesota spatial registry and dashboard geometry."""

from typing import Dict

from src.spatial.submarkets import BoroughMeta, SubmarketMeta


MINNEAPOLIS_METRO_BBOX: Dict[str, float] = {
    "min_lat": 44.85,
    "max_lat": 45.08,
    "min_lng": -93.36,
    "max_lng": -93.15,
}

MINNEAPOLIS_DIVISION_BBOXES: Dict[str, Dict[str, float]] = {
    "NORTH": {
        "min_lat": 44.97,
        "max_lat": 45.06,
        "min_lng": -93.34,
        "max_lng": -93.22,
    },
    "NORTHEAST": {
        "min_lat": 44.98,
        "max_lat": 45.08,
        "min_lng": -93.26,
        "max_lng": -93.18,
    },
    "CENTRAL": {
        "min_lat": 44.95,
        "max_lat": 45.02,
        "min_lng": -93.30,
        "max_lng": -93.24,
    },
    "SOUTH": {
        "min_lat": 44.89,
        "max_lat": 44.97,
        "min_lng": -93.30,
        "max_lng": -93.22,
    },
    "SOUTHWEST": {
        "min_lat": 44.90,
        "max_lat": 44.98,
        "min_lng": -93.35,
        "max_lng": -93.27,
    },
    "SOUTHEAST": {
        "min_lat": 44.94,
        "max_lat": 45.02,
        "min_lng": -93.24,
        "max_lng": -93.19,
    },
}


def is_in_minneapolis_metro(lat: float, lng: float) -> bool:
    """Return whether a coordinate lies inside the registered Minneapolis extent."""
    if lat is None or lng is None:
        return False
    return (
        MINNEAPOLIS_METRO_BBOX["min_lat"] <= lat <= MINNEAPOLIS_METRO_BBOX["max_lat"]
        and MINNEAPOLIS_METRO_BBOX["min_lng"] <= lng <= MINNEAPOLIS_METRO_BBOX["max_lng"]
    )


MINNEAPOLIS_SUBMARKETS: Dict[str, SubmarketMeta] = {
    "Camden": SubmarketMeta(
        name="Camden",
        borough="NORTH",
        lat=45.0430,
        lng=-93.3030,
        zoom=12.6,
        pitch=46.0,
        base_lims=0.74,
        capex=3800000.0,
        permit_vel=22.0,
        shift_ratio=1.32,
        sla=51.0,
        description="Northern residential district along the Mississippi with modest redevelopment and home-renovation permit activity.",
        city_id="minneapolis",
    ),
    "Near North": SubmarketMeta(
        name="Near North",
        borough="NORTH",
        lat=44.9960,
        lng=-93.2770,
        zoom=12.8,
        pitch=46.0,
        base_lims=0.79,
        capex=4900000.0,
        permit_vel=28.0,
        shift_ratio=1.38,
        sla=54.0,
        description="North-central neighborhood corridor with mixed-use infill, senior-housing and commercial rehab signals.",
        city_id="minneapolis",
    ),
    "Northeast": SubmarketMeta(
        name="Northeast",
        borough="NORTHEAST",
        lat=45.0130,
        lng=-93.2180,
        zoom=12.4,
        pitch=44.0,
        base_lims=0.83,
        capex=6100000.0,
        permit_vel=34.0,
        shift_ratio=1.44,
        sla=58.0,
        description="Arts-district river community with dense multifamily infill and ongoing warehouse-to-residential conversions.",
        city_id="minneapolis",
    ),
    "Nicollet Island-East Bank": SubmarketMeta(
        name="Nicollet Island-East Bank",
        borough="NORTHEAST",
        lat=44.9850,
        lng=-93.2560,
        zoom=13.2,
        pitch=50.0,
        base_lims=0.85,
        capex=7400000.0,
        permit_vel=38.0,
        shift_ratio=1.47,
        sla=62.0,
        description="Historic river-island enclave with boutique multifamily and adaptive-reuse development.",
        city_id="minneapolis",
    ),
    "Downtown West": SubmarketMeta(
        name="Downtown West",
        borough="CENTRAL",
        lat=44.9770,
        lng=-93.2730,
        zoom=13.2,
        pitch=52.0,
        base_lims=0.89,
        capex=11800000.0,
        permit_vel=52.0,
        shift_ratio=1.55,
        sla=68.0,
        description="Central business district with the region's densest office, hospitality, and high-rise residential permit pipeline.",
        city_id="minneapolis",
    ),
    "Downtown East": SubmarketMeta(
        name="Downtown East",
        borough="CENTRAL",
        lat=44.9750,
        lng=-93.2570,
        zoom=13.2,
        pitch=50.0,
        base_lims=0.87,
        capex=9600000.0,
        permit_vel=46.0,
        shift_ratio=1.51,
        sla=65.0,
        description="East-of-Mississippi downtown pocket anchored by stadium, medical, and emerging residential development.",
        city_id="minneapolis",
    ),
    "Cedar-Riverside": SubmarketMeta(
        name="Cedar-Riverside",
        borough="CENTRAL",
        lat=44.9700,
        lng=-93.2470,
        zoom=12.8,
        pitch=44.0,
        base_lims=0.81,
        capex=5200000.0,
        permit_vel=30.0,
        shift_ratio=1.41,
        sla=57.0,
        description="Vibrant, densely populated neighborhood with ongoing housing rehabilitation and institutional anchors.",
        city_id="minneapolis",
    ),
    "Powderhorn": SubmarketMeta(
        name="Powderhorn",
        borough="SOUTH",
        lat=44.9410,
        lng=-93.2560,
        zoom=12.8,
        pitch=44.0,
        base_lims=0.76,
        capex=4100000.0,
        permit_vel=24.0,
        shift_ratio=1.34,
        sla=52.0,
        description="Established residential district with steady single-family rehab and neighborhood commercial renewal.",
        city_id="minneapolis",
    ),
    "Phillips": SubmarketMeta(
        name="Phillips",
        borough="SOUTH",
        lat=44.9560,
        lng=-93.2680,
        zoom=12.6,
        pitch=44.0,
        base_lims=0.78,
        capex=4600000.0,
        permit_vel=26.0,
        shift_ratio=1.36,
        sla=53.0,
        description="Inner-south neighborhood with concentrated community-driven housing and small-biz revitalization.",
        city_id="minneapolis",
    ),
    "Uptown": SubmarketMeta(
        name="Uptown",
        borough="SOUTHWEST",
        lat=44.9510,
        lng=-93.2980,
        zoom=13.0,
        pitch=48.0,
        base_lims=0.86,
        capex=8200000.0,
        permit_vel=40.0,
        shift_ratio=1.49,
        sla=61.0,
        description="High-street retail and multifamily district with steady mixed-use infill and commercial renovation activity.",
        city_id="minneapolis",
    ),
    "Linden Hills": SubmarketMeta(
        name="Linden Hills",
        borough="SOUTHWEST",
        lat=44.9330,
        lng=-93.3070,
        zoom=13.0,
        pitch=44.0,
        base_lims=0.84,
        capex=6900000.0,
        permit_vel=35.0,
        shift_ratio=1.45,
        sla=59.0,
        description="Lake-adjacent residential village with upscale renovation and small commercial reinvestment.",
        city_id="minneapolis",
    ),
    "University / Marcy-Holmes": SubmarketMeta(
        name="University / Marcy-Holmes",
        borough="SOUTHEAST",
        lat=44.9820,
        lng=-93.2400,
        zoom=12.8,
        pitch=44.0,
        base_lims=0.85,
        capex=7800000.0,
        permit_vel=39.0,
        shift_ratio=1.46,
        sla=60.0,
        description="U of M-adjacent corridor with dense student-housing infill and institutional-adjacent development.",
        city_id="minneapolis",
    ),
    "Prospect Park": SubmarketMeta(
        name="Prospect Park",
        borough="SOUTHEAST",
        lat=44.9730,
        lng=-93.2150,
        zoom=12.6,
        pitch=44.0,
        base_lims=0.82,
        capex=5700000.0,
        permit_vel=32.0,
        shift_ratio=1.43,
        sla=57.0,
        description="Tower-side neighborhood with planned infill and ongoing single-family and duplex renovation.",
        city_id="minneapolis",
    ),
}

MINNEAPOLIS_DIVISIONS: Dict[str, BoroughMeta] = {
    "NORTH": BoroughMeta(
        name="North Minneapolis",
        center_lat=45.0100,
        center_lng=-93.2800,
        zoom=11.8,
        bbox=MINNEAPOLIS_DIVISION_BBOXES["NORTH"],
        submarkets=["Camden", "Near North"],
        city_id="minneapolis",
    ),
    "NORTHEAST": BoroughMeta(
        name="Northeast",
        center_lat=45.0200,
        center_lng=-93.2300,
        zoom=11.8,
        bbox=MINNEAPOLIS_DIVISION_BBOXES["NORTHEAST"],
        submarkets=["Northeast", "Nicollet Island-East Bank"],
        city_id="minneapolis",
    ),
    "CENTRAL": BoroughMeta(
        name="Central Minneapolis",
        center_lat=44.9770,
        center_lng=-93.2650,
        zoom=11.6,
        bbox=MINNEAPOLIS_DIVISION_BBOXES["CENTRAL"],
        submarkets=["Downtown West", "Downtown East", "Cedar-Riverside"],
        city_id="minneapolis",
    ),
    "SOUTH": BoroughMeta(
        name="South Minneapolis",
        center_lat=44.9400,
        center_lng=-93.2600,
        zoom=11.8,
        bbox=MINNEAPOLIS_DIVISION_BBOXES["SOUTH"],
        submarkets=["Powderhorn", "Phillips"],
        city_id="minneapolis",
    ),
    "SOUTHWEST": BoroughMeta(
        name="Southwest Minneapolis",
        center_lat=44.9400,
        center_lng=-93.3100,
        zoom=11.8,
        bbox=MINNEAPOLIS_DIVISION_BBOXES["SOUTHWEST"],
        submarkets=["Uptown", "Linden Hills"],
        city_id="minneapolis",
    ),
    "SOUTHEAST": BoroughMeta(
        name="Southeast Minneapolis",
        center_lat=44.9750,
        center_lng=-93.2200,
        zoom=11.8,
        bbox=MINNEAPOLIS_DIVISION_BBOXES["SOUTHEAST"],
        submarkets=["University / Marcy-Holmes", "Prospect Park"],
        city_id="minneapolis",
    ),
}

from src.spatial.registration import SpatialRegistration

REGISTRATION = SpatialRegistration(
    metro_bbox=MINNEAPOLIS_METRO_BBOX,
    division_bboxes=MINNEAPOLIS_DIVISION_BBOXES,
    submarkets=MINNEAPOLIS_SUBMARKETS,
    divisions=MINNEAPOLIS_DIVISIONS,
    contains=is_in_minneapolis_metro,
)
