"""San Diego, California spatial registry and dashboard geometry."""

from typing import Dict

from src.spatial.submarkets import BoroughMeta, SubmarketMeta


SAN_DIEGO_METRO_BBOX: Dict[str, float] = {
    "min_lat": 32.50,
    "max_lat": 33.10,
    "min_lng": -117.35,
    "max_lng": -116.85,
}

SAN_DIEGO_DIVISION_BBOXES: Dict[str, Dict[str, float]] = {
    "NORTH": {
        "min_lat": 32.80,
        "max_lat": 33.08,
        "min_lng": -117.30,
        "max_lng": -117.05,
    },
    "COASTAL": {
        "min_lat": 32.68,
        "max_lat": 32.90,
        "min_lng": -117.30,
        "max_lng": -117.18,
    },
    "CENTRAL": {
        "min_lat": 32.70,
        "max_lat": 32.80,
        "min_lng": -117.20,
        "max_lng": -117.10,
    },
    "EAST": {
        "min_lat": 32.74,
        "max_lat": 33.05,
        "min_lng": -117.15,
        "max_lng": -116.90,
    },
    "SOUTHEAST": {
        "min_lat": 32.60,
        "max_lat": 32.75,
        "min_lng": -117.15,
        "max_lng": -116.90,
    },
    "SOUTHWEST": {
        "min_lat": 32.50,
        "max_lat": 32.68,
        "min_lng": -117.20,
        "max_lng": -116.90,
    },
}


def is_in_san_diego_metro(lat: float, lng: float) -> bool:
    """Return whether a coordinate lies inside the registered San Diego extent."""
    if lat is None or lng is None:
        return False
    return (
        SAN_DIEGO_METRO_BBOX["min_lat"] <= lat <= SAN_DIEGO_METRO_BBOX["max_lat"]
        and SAN_DIEGO_METRO_BBOX["min_lng"] <= lng <= SAN_DIEGO_METRO_BBOX["max_lng"]
    )


SAN_DIEGO_SUBMARKETS: Dict[str, SubmarketMeta] = {
    "La Jolla": SubmarketMeta(
        name="La Jolla",
        borough="NORTH",
        lat=32.8328,
        lng=-117.2713,
        zoom=12.6,
        pitch=46.0,
        base_lims=0.92,
        capex=9200000.0,
        permit_vel=38.0,
        shift_ratio=1.28,
        sla=44.0,
        description="Coastal science-and-affluence district with biotech labs, low-rise multifamily, and high-value residential redevelopment.",
        city_id="san_diego",
    ),
    "Mira Mesa": SubmarketMeta(
        name="Mira Mesa",
        borough="NORTH",
        lat=32.9167,
        lng=-117.1433,
        zoom=12.4,
        pitch=44.0,
        base_lims=0.78,
        capex=6200000.0,
        permit_vel=34.0,
        shift_ratio=1.36,
        sla=52.0,
        description="Tech-corridor residential plateau with steady infill, office-to-residential conversions, and planning-permit activity.",
        city_id="san_diego",
    ),
    "Pacific Beach": SubmarketMeta(
        name="Pacific Beach",
        borough="COASTAL",
        lat=32.7977,
        lng=-117.2408,
        zoom=13.0,
        pitch=48.0,
        base_lims=0.85,
        capex=7400000.0,
        permit_vel=40.0,
        shift_ratio=1.42,
        sla=58.0,
        description="Beach-adjacent rental district with multifamily infill, short-term-rental churn, and steady interior renovation.",
        city_id="san_diego",
    ),
    "Ocean Beach": SubmarketMeta(
        name="Ocean Beach",
        borough="COASTAL",
        lat=32.7513,
        lng=-117.2498,
        zoom=12.8,
        pitch=46.0,
        base_lims=0.81,
        capex=5100000.0,
        permit_vel=28.0,
        shift_ratio=1.34,
        sla=51.0,
        description="Bohemian coastal village with modest single-family rehab, cottage infill, and long-standing neighborhood retail.",
        city_id="san_diego",
    ),
    "Downtown": SubmarketMeta(
        name="Downtown",
        borough="CENTRAL",
        lat=32.7157,
        lng=-117.1611,
        zoom=13.2,
        pitch=52.0,
        base_lims=0.94,
        capex=14800000.0,
        permit_vel=64.0,
        shift_ratio=1.58,
        sla=71.0,
        description="CBD and East Village high-rise pipeline — office, hospitality, residential towers, and the densest permitting in the metro.",
        city_id="san_diego",
    ),
    "North Park": SubmarketMeta(
        name="North Park",
        borough="CENTRAL",
        lat=32.7365,
        lng=-117.1228,
        zoom=13.0,
        pitch=48.0,
        base_lims=0.86,
        capex=8200000.0,
        permit_vel=44.0,
        shift_ratio=1.47,
        sla=63.0,
        description="Urban-village commercial corridor with dense multifamily infill, adaptive reuse, and steady mixed-use permitting.",
        city_id="san_diego",
    ),
    "Kearny Mesa": SubmarketMeta(
        name="Kearny Mesa",
        borough="EAST",
        lat=32.8135,
        lng=-117.1331,
        zoom=12.4,
        pitch=44.0,
        base_lims=0.80,
        capex=6400000.0,
        permit_vel=36.0,
        shift_ratio=1.35,
        sla=48.0,
        description="Auto-row and light-industrial district with warehouse conversions, commercial buildouts, and logistics infill.",
        city_id="san_diego",
    ),
    "Mission Valley": SubmarketMeta(
        name="Mission Valley",
        borough="EAST",
        lat=32.7761,
        lng=-117.1113,
        zoom=12.8,
        pitch=46.0,
        base_lims=0.88,
        capex=9800000.0,
        permit_vel=48.0,
        shift_ratio=1.45,
        sla=56.0,
        description="River-valley corridor of large mixed-use and commercial redevelopment along the transit spine.",
        city_id="san_diego",
    ),
    "Logan Heights": SubmarketMeta(
        name="Logan Heights",
        borough="SOUTHEAST",
        lat=32.7008,
        lng=-117.1077,
        zoom=12.6,
        pitch=44.0,
        base_lims=0.74,
        capex=4600000.0,
        permit_vel=26.0,
        shift_ratio=1.30,
        sla=50.0,
        description="Historic barrio east of downtown with community-driven infill, ADU programs, and small commercial renewal.",
        city_id="san_diego",
    ),
    "Encanto": SubmarketMeta(
        name="Encanto",
        borough="SOUTHEAST",
        lat=32.7092,
        lng=-117.0775,
        zoom=12.4,
        pitch=44.0,
        base_lims=0.72,
        capex=3900000.0,
        permit_vel=22.0,
        shift_ratio=1.27,
        sla=49.0,
        description="Inner-southeast residential district with single-family rehab, ADU activity, and modest retail reinvestment.",
        city_id="san_diego",
    ),
    "Otay Mesa": SubmarketMeta(
        name="Otay Mesa",
        borough="SOUTHWEST",
        lat=32.5537,
        lng=-117.0440,
        zoom=12.2,
        pitch=44.0,
        base_lims=0.76,
        capex=5800000.0,
        permit_vel=32.0,
        shift_ratio=1.31,
        sla=41.0,
        description="Border industrial and logistics mesa with warehouse construction, distribution centers, and border-economy churn.",
        city_id="san_diego",
    ),
    "San Ysidro": SubmarketMeta(
        name="San Ysidro",
        borough="SOUTHWEST",
        lat=32.5430,
        lng=-117.0520,
        zoom=12.6,
        pitch=46.0,
        base_lims=0.70,
        capex=3400000.0,
        permit_vel=20.0,
        shift_ratio=1.24,
        sla=46.0,
        description="Border gateway neighborhood with mixed-use infill around the port of entry and steady small-commercial permits.",
        city_id="san_diego",
    ),
}

SAN_DIEGO_DIVISIONS: Dict[str, BoroughMeta] = {
    "NORTH": BoroughMeta(
        name="North San Diego",
        center_lat=32.87,
        center_lng=-117.20,
        zoom=11.6,
        bbox=SAN_DIEGO_DIVISION_BBOXES["NORTH"],
        submarkets=["La Jolla", "Mira Mesa"],
        city_id="san_diego",
    ),
    "COASTAL": BoroughMeta(
        name="Coastal San Diego",
        center_lat=32.79,
        center_lng=-117.25,
        zoom=11.6,
        bbox=SAN_DIEGO_DIVISION_BBOXES["COASTAL"],
        submarkets=["Pacific Beach", "Ocean Beach"],
        city_id="san_diego",
    ),
    "CENTRAL": BoroughMeta(
        name="Central San Diego",
        center_lat=32.74,
        center_lng=-117.16,
        zoom=11.4,
        bbox=SAN_DIEGO_DIVISION_BBOXES["CENTRAL"],
        submarkets=["Downtown", "North Park"],
        city_id="san_diego",
    ),
    "EAST": BoroughMeta(
        name="East San Diego",
        center_lat=32.82,
        center_lng=-117.05,
        zoom=11.6,
        bbox=SAN_DIEGO_DIVISION_BBOXES["EAST"],
        submarkets=["Kearny Mesa", "Mission Valley"],
        city_id="san_diego",
    ),
    "SOUTHEAST": BoroughMeta(
        name="Southeast San Diego",
        center_lat=32.68,
        center_lng=-117.03,
        zoom=11.6,
        bbox=SAN_DIEGO_DIVISION_BBOXES["SOUTHEAST"],
        submarkets=["Logan Heights", "Encanto"],
        city_id="san_diego",
    ),
    "SOUTHWEST": BoroughMeta(
        name="South Bay San Diego",
        center_lat=32.55,
        center_lng=-117.03,
        zoom=11.4,
        bbox=SAN_DIEGO_DIVISION_BBOXES["SOUTHWEST"],
        submarkets=["Otay Mesa", "San Ysidro"],
        city_id="san_diego",
    ),
}