"""San Francisco Bay Area Submarket Registry and Spatial Layer for Urban Signal.

Provides comprehensive neighborhood metadata, camera positioning, investment
metrics, division catalog, and geographic bounding boxes for the SF Bay Area, CA.
"""

from typing import Dict
from src.spatial.submarkets import BoroughMeta, SubmarketMeta

# SF Bay Area Metro overall bounding box
SF_METRO_BBOX: Dict[str, float] = {
    "min_lat": 37.15,
    "max_lat": 38.10,
    "min_lng": -122.65,
    "max_lng": -121.75,
}
SAN_FRANCISCO_METRO_BBOX = SF_METRO_BBOX

# 5 San Francisco Bay Area Division Bounding Boxes
SF_DIVISION_BBOXES: Dict[str, Dict[str, float]] = {
    "SAN_FRANCISCO_CORE":       {"min_lat": 37.700, "max_lat": 37.835, "min_lng": -122.525, "max_lng": -122.355},
    "EAST_BAY":                 {"min_lat": 37.450, "max_lat": 38.050, "min_lng": -122.400, "max_lng": -121.750},
    "PENINSULA":                {"min_lat": 37.420, "max_lat": 37.700, "min_lng": -122.520, "max_lng": -122.180},
    "SILICON_VALLEY_SOUTH_BAY": {"min_lat": 37.150, "max_lat": 37.460, "min_lng": -122.200, "max_lng": -121.750},
    "MARIN_NORTH_BAY":          {"min_lat": 37.835, "max_lat": 38.100, "min_lng": -122.650, "max_lng": -122.400},
}
SAN_FRANCISCO_DIVISION_BBOXES = SF_DIVISION_BBOXES


def is_in_sf_metro(lat: float, lng: float) -> bool:
    """Check if a coordinate lies within the San Francisco Bay Area Metropolitan bounds."""
    return (
        SF_METRO_BBOX["min_lat"] <= lat <= SF_METRO_BBOX["max_lat"]
        and SF_METRO_BBOX["min_lng"] <= lng <= SF_METRO_BBOX["max_lng"]
    )


is_in_san_francisco_metro = is_in_sf_metro


# ---------------------------------------------------------------------------
# Comprehensive San Francisco Submarket Registry (41 Submarkets Across 5 Divisions)
# ---------------------------------------------------------------------------

SAN_FRANCISCO_SUBMARKETS: Dict[str, SubmarketMeta] = {
    # =======================================================================
    # SAN_FRANCISCO_CORE (17 Submarkets)
    # =======================================================================
    "Downtown": SubmarketMeta(
        name="Downtown",
        borough="SAN_FRANCISCO_CORE",
        lat=37.7879,
        lng=-122.4074,
        zoom=14.5,
        pitch=55.0,
        base_lims=0.88,
        capex=12500000.0,
        permit_vel=52.0,
        shift_ratio=1.50,
        sla=60.0,
        description="San Francisco central retail and commercial corridor anchored by Union Square, Market Street transit, and high-density hotel flagships.",
        city_id="san_francisco",
    ),
    "SoMa": SubmarketMeta(
        name="SoMa",
        borough="SAN_FRANCISCO_CORE",
        lat=37.7785,
        lng=-122.3950,
        zoom=14.5,
        pitch=55.0,
        base_lims=0.92,
        capex=14000000.0,
        permit_vel=64.0,
        shift_ratio=1.68,
        sla=70.0,
        description="South of Market tech campus core and cultural anchor with high-density residential towers, Moscone Center, and adaptive warehouse conversions.",
        city_id="san_francisco",
    ),
    "Financial District": SubmarketMeta(
        name="Financial District",
        borough="SAN_FRANCISCO_CORE",
        lat=37.7946,
        lng=-122.4000,
        zoom=14.5,
        pitch=60.0,
        base_lims=0.90,
        capex=15000000.0,
        permit_vel=48.0,
        shift_ratio=1.58,
        sla=55.0,
        description="West Coast banking capital and high-rise commercial hub featuring the Transamerica Pyramid, Salesforce Tower, and premium office towers.",
        city_id="san_francisco",
    ),
    "Mission": SubmarketMeta(
        name="Mission",
        borough="SAN_FRANCISCO_CORE",
        lat=37.7599,
        lng=-122.4148,
        zoom=14.5,
        pitch=45.0,
        base_lims=0.89,
        capex=8800000.0,
        permit_vel=56.0,
        shift_ratio=1.55,
        sla=78.0,
        description="Historic cultural and culinary corridor centered on Valencia and Mission streets with vibrant murals, Michelin-starred dining, and transit access.",
        city_id="san_francisco",
    ),
    "Hayes Valley": SubmarketMeta(
        name="Hayes Valley",
        borough="SAN_FRANCISCO_CORE",
        lat=37.7758,
        lng=-122.4245,
        zoom=15.0,
        pitch=45.0,
        base_lims=0.87,
        capex=7800000.0,
        permit_vel=44.0,
        shift_ratio=1.42,
        sla=68.0,
        description="Boutique shopping and arts enclave adjacent to the Civic Center performing arts complex with high pedestrian activity and designer retail.",
        city_id="san_francisco",
    ),
    "Marina": SubmarketMeta(
        name="Marina",
        borough="SAN_FRANCISCO_CORE",
        lat=37.8037,
        lng=-122.4368,
        zoom=14.5,
        pitch=40.0,
        base_lims=0.86,
        capex=8200000.0,
        permit_vel=38.0,
        shift_ratio=1.36,
        sla=72.0,
        description="Scenic bayfront district featuring Mediterranean-style architecture, Chestnut Street shopping, Palace of Fine Arts, and Marina Green parkland.",
        city_id="san_francisco",
    ),
    "Mission Bay": SubmarketMeta(
        name="Mission Bay",
        borough="SAN_FRANCISCO_CORE",
        lat=37.7710,
        lng=-122.3912,
        zoom=14.5,
        pitch=50.0,
        base_lims=0.94,
        capex=13500000.0,
        permit_vel=68.0,
        shift_ratio=1.72,
        sla=62.0,
        description="Master-planned life sciences and healthcare district anchored by UCSF Mission Bay medical campus and the Golden State Warriors Chase Center.",
        city_id="san_francisco",
    ),
    "Dogpatch": SubmarketMeta(
        name="Dogpatch",
        borough="SAN_FRANCISCO_CORE",
        lat=37.7587,
        lng=-122.3876,
        zoom=14.5,
        pitch=45.0,
        base_lims=0.84,
        capex=8000000.0,
        permit_vel=50.0,
        shift_ratio=1.46,
        sla=58.0,
        description="Historic maritime and industrial neighborhood along Third Street transformed into an artisanal manufacturing, brewery, and contemporary loft district.",
        city_id="san_francisco",
    ),
    "Potrero Hill": SubmarketMeta(
        name="Potrero Hill",
        borough="SAN_FRANCISCO_CORE",
        lat=37.7580,
        lng=-122.4005,
        zoom=14.0,
        pitch=45.0,
        base_lims=0.83,
        capex=7500000.0,
        permit_vel=42.0,
        shift_ratio=1.38,
        sla=50.0,
        description="Sunny residential neighborhood with dramatic skyline vistas, 18th Street village retail, and design showroom conversions.",
        city_id="san_francisco",
    ),
    "North Beach": SubmarketMeta(
        name="North Beach",
        borough="SAN_FRANCISCO_CORE",
        lat=37.8005,
        lng=-122.4098,
        zoom=14.5,
        pitch=45.0,
        base_lims=0.85,
        capex=7900000.0,
        permit_vel=36.0,
        shift_ratio=1.34,
        sla=82.0,
        description="San Francisco's historic Little Italy and Beat Generation enclave along Columbus Avenue with dense trattorias, cafes, and historic nightlife.",
        city_id="san_francisco",
    ),
    "Pacific Heights": SubmarketMeta(
        name="Pacific Heights",
        borough="SAN_FRANCISCO_CORE",
        lat=37.7925,
        lng=-122.4352,
        zoom=14.0,
        pitch=45.0,
        base_lims=0.91,
        capex=11500000.0,
        permit_vel=32.0,
        shift_ratio=1.28,
        sla=52.0,
        description="Prestigious hilltop enclave known for Billionaire's Row mansions, Fillmore Street upscale retail, and sweeping views of the Golden Gate.",
        city_id="san_francisco",
    ),
    "Castro": SubmarketMeta(
        name="Castro",
        borough="SAN_FRANCISCO_CORE",
        lat=37.7609,
        lng=-122.4350,
        zoom=14.5,
        pitch=45.0,
        base_lims=0.85,
        capex=7600000.0,
        permit_vel=46.0,
        shift_ratio=1.40,
        sla=76.0,
        description="World-renowned historic LGBTQ+ cultural capital centered on Castro and 18th streets with iconic Victorian architecture and active retail corridors.",
        city_id="san_francisco",
    ),
    "Sunset": SubmarketMeta(
        name="Sunset",
        borough="SAN_FRANCISCO_CORE",
        lat=37.7535,
        lng=-122.4830,
        zoom=13.5,
        pitch=35.0,
        base_lims=0.78,
        capex=5400000.0,
        permit_vel=34.0,
        shift_ratio=1.22,
        sla=40.0,
        description="Expansive coastal residential district bordered by Golden Gate Park and Ocean Beach with vibrant commercial spines on Irving, Judah, and Noriega.",
        city_id="san_francisco",
    ),
    "Richmond": SubmarketMeta(
        name="Richmond",
        borough="SAN_FRANCISCO_CORE",
        lat=37.7795,
        lng=-122.4740,
        zoom=13.5,
        pitch=35.0,
        base_lims=0.79,
        capex=5600000.0,
        permit_vel=35.0,
        shift_ratio=1.24,
        sla=46.0,
        description="Northwest residential district along Clement and Geary boulevards featuring exceptional culinary diversity, park access, and multi-family infill.",
        city_id="san_francisco",
    ),
    "Nob Hill": SubmarketMeta(
        name="Nob Hill",
        borough="SAN_FRANCISCO_CORE",
        lat=37.7920,
        lng=-122.4150,
        zoom=14.5,
        pitch=50.0,
        base_lims=0.88,
        capex=9200000.0,
        permit_vel=37.0,
        shift_ratio=1.35,
        sla=64.0,
        description="Historic luxury hilltop neighborhood crowned by landmark hotels (Fairmont, Mark Hopkins), Grace Cathedral, and historic cable car lines.",
        city_id="san_francisco",
    ),
    "Tenderloin": SubmarketMeta(
        name="Tenderloin",
        borough="SAN_FRANCISCO_CORE",
        lat=37.7833,
        lng=-122.4167,
        zoom=14.5,
        pitch=45.0,
        base_lims=0.72,
        capex=4600000.0,
        permit_vel=49.0,
        shift_ratio=1.38,
        sla=54.0,
        description="Historic central district featuring dense SRO and apartment stock, Little Saigon culinary spine, and emerging arts venues.",
        city_id="san_francisco",
    ),
    "Presidio": SubmarketMeta(
        name="Presidio",
        borough="SAN_FRANCISCO_CORE",
        lat=37.7989,
        lng=-122.4662,
        zoom=13.5,
        pitch=40.0,
        base_lims=0.82,
        capex=6800000.0,
        permit_vel=25.0,
        shift_ratio=1.20,
        sla=35.0,
        description="Former military garrison turned iconic national parkland with historic officer quarters, Lucasfilm campus, and Presidio Tunnel Tops.",
        city_id="san_francisco",
    ),

    # =======================================================================
    # EAST_BAY (9 Submarkets)
    # =======================================================================
    "Downtown Oakland": SubmarketMeta(
        name="Downtown Oakland",
        borough="EAST_BAY",
        lat=37.8044,
        lng=-122.2711,
        zoom=14.5,
        pitch=50.0,
        base_lims=0.86,
        capex=9800000.0,
        permit_vel=58.0,
        shift_ratio=1.56,
        sla=62.0,
        description="Civic and commercial heart of the East Bay centered around City Center, BART transit hub, and major residential high-rises.",
        city_id="san_francisco",
    ),
    "Uptown Oakland": SubmarketMeta(
        name="Uptown Oakland",
        borough="EAST_BAY",
        lat=37.8105,
        lng=-122.2685,
        zoom=14.5,
        pitch=50.0,
        base_lims=0.88,
        capex=9400000.0,
        permit_vel=60.0,
        shift_ratio=1.60,
        sla=76.0,
        description="Premier entertainment and arts district featuring the Fox and Paramount Theatres, Telegraph Avenue dining, and creative headquarters.",
        city_id="san_francisco",
    ),
    "Jack London Square": SubmarketMeta(
        name="Jack London Square",
        borough="EAST_BAY",
        lat=37.7946,
        lng=-122.2764,
        zoom=14.5,
        pitch=45.0,
        base_lims=0.82,
        capex=7800000.0,
        permit_vel=45.0,
        shift_ratio=1.42,
        sla=58.0,
        description="Historic waterfront dining, ferry terminal, and logistics-adjacent development corridor along the Oakland Estuary.",
        city_id="san_francisco",
    ),
    "Berkeley Downtown": SubmarketMeta(
        name="Berkeley Downtown",
        borough="EAST_BAY",
        lat=37.8703,
        lng=-122.2681,
        zoom=14.5,
        pitch=45.0,
        base_lims=0.87,
        capex=8900000.0,
        permit_vel=52.0,
        shift_ratio=1.48,
        sla=56.0,
        description="UC Berkeley gateway and transit center with Shattuck Avenue retail, Berkeley Rep arts anchors, and dense student housing development.",
        city_id="san_francisco",
    ),
    "West Berkeley": SubmarketMeta(
        name="West Berkeley",
        borough="EAST_BAY",
        lat=37.8680,
        lng=-122.2980,
        zoom=14.0,
        pitch=40.0,
        base_lims=0.81,
        capex=6900000.0,
        permit_vel=44.0,
        shift_ratio=1.38,
        sla=48.0,
        description="Artisanal, biotech, and retail corridor along Fourth Street with light industrial conversions and innovative makerspaces.",
        city_id="san_francisco",
    ),
    "Rockridge": SubmarketMeta(
        name="Rockridge",
        borough="EAST_BAY",
        lat=37.8444,
        lng=-122.2518,
        zoom=14.5,
        pitch=40.0,
        base_lims=0.85,
        capex=7200000.0,
        permit_vel=34.0,
        shift_ratio=1.30,
        sla=52.0,
        description="Affluent North Oakland neighborhood along College Avenue featuring gourmet dining, bookstore boutiques, and BART transit connectivity.",
        city_id="san_francisco",
    ),
    "Temescal": SubmarketMeta(
        name="Temescal",
        borough="EAST_BAY",
        lat=37.8347,
        lng=-122.2638,
        zoom=14.5,
        pitch=40.0,
        base_lims=0.83,
        capex=6700000.0,
        permit_vel=48.0,
        shift_ratio=1.44,
        sla=64.0,
        description="Trendy culinary corridor along Telegraph Avenue featuring Temescal Alleys, artisanal food scene, and transit-oriented infill.",
        city_id="san_francisco",
    ),
    "Emeryville": SubmarketMeta(
        name="Emeryville",
        borough="EAST_BAY",
        lat=37.8313,
        lng=-122.2852,
        zoom=14.0,
        pitch=45.0,
        base_lims=0.85,
        capex=9100000.0,
        permit_vel=55.0,
        shift_ratio=1.52,
        sla=54.0,
        description="Biotech, animation (Pixar), and major retail center between Oakland and Berkeley with high-density mixed-use development.",
        city_id="san_francisco",
    ),
    "Alameda": SubmarketMeta(
        name="Alameda",
        borough="EAST_BAY",
        lat=37.7652,
        lng=-122.2416,
        zoom=13.5,
        pitch=35.0,
        base_lims=0.80,
        capex=6200000.0,
        permit_vel=36.0,
        shift_ratio=1.28,
        sla=44.0,
        description="Island city community known for Victorian architecture, historic Park and Webster street retail, and Alameda Point waterfront reuse.",
        city_id="san_francisco",
    ),
    "Fremont Downtown": SubmarketMeta(
        name="Fremont Downtown",
        borough="EAST_BAY",
        lat=37.5485,
        lng=-121.9886,
        zoom=14.0,
        pitch=40.0,
        base_lims=0.85,
        capex=8500000.0,
        permit_vel=45.0,
        shift_ratio=1.40,
        sla=52.0,
        description="Major East Bay tech manufacturing and residential hub centered around Capitol Avenue, BART, and Tesla Gigafactory corridor.",
        city_id="san_francisco",
    ),
    "Hayward Downtown": SubmarketMeta(
        name="Hayward Downtown",
        borough="EAST_BAY",
        lat=37.6688,
        lng=-122.0808,
        zoom=14.0,
        pitch=40.0,
        base_lims=0.79,
        capex=6100000.0,
        permit_vel=38.0,
        shift_ratio=1.30,
        sla=42.0,
        description="Central East Bay transit corridor featuring historic B Street revitalization, Cal State East Bay connectivity, and mixed-use housing.",
        city_id="san_francisco",
    ),
    "San Leandro Downtown": SubmarketMeta(
        name="San Leandro Downtown",
        borough="EAST_BAY",
        lat=37.7249,
        lng=-122.1561,
        zoom=14.0,
        pitch=35.0,
        base_lims=0.80,
        capex=6400000.0,
        permit_vel=40.0,
        shift_ratio=1.32,
        sla=46.0,
        description="Tech campus and 3D printing/industrial tech center along East 14th Street with TOD development near BART.",
        city_id="san_francisco",
    ),
    "Richmond CA": SubmarketMeta(
        name="Richmond CA",
        borough="EAST_BAY",
        lat=37.9358,
        lng=-122.3477,
        zoom=13.5,
        pitch=35.0,
        base_lims=0.76,
        capex=5400000.0,
        permit_vel=37.0,
        shift_ratio=1.27,
        sla=40.0,
        description="North Bay / East Bay gateway featuring Macdonald Avenue revitalization, Richmond Ferry Terminal, and waterfront industrial reuse.",
        city_id="san_francisco",
    ),
    "Walnut Creek Downtown": SubmarketMeta(
        name="Walnut Creek Downtown",
        borough="EAST_BAY",
        lat=37.9101,
        lng=-122.0652,
        zoom=14.5,
        pitch=45.0,
        base_lims=0.88,
        capex=9200000.0,
        permit_vel=46.0,
        shift_ratio=1.45,
        sla=58.0,
        description="Premier Contra Costa commercial and luxury shopping destination anchored by Broadway Plaza, high-density residential, and BART.",
        city_id="san_francisco",
    ),
    "Concord Downtown": SubmarketMeta(
        name="Concord Downtown",
        borough="EAST_BAY",
        lat=37.9780,
        lng=-122.0311,
        zoom=14.0,
        pitch=40.0,
        base_lims=0.81,
        capex=6700000.0,
        permit_vel=42.0,
        shift_ratio=1.34,
        sla=48.0,
        description="Todos Santos Plaza dining and community core with major BART connectivity and regional transit-oriented infill.",
        city_id="san_francisco",
    ),
    "Pleasanton Downtown": SubmarketMeta(
        name="Pleasanton Downtown",
        borough="EAST_BAY",
        lat=37.6624,
        lng=-121.8747,
        zoom=14.0,
        pitch=40.0,
        base_lims=0.87,
        capex=8800000.0,
        permit_vel=44.0,
        shift_ratio=1.42,
        sla=54.0,
        description="Historic Main Street Tri-Valley enclave and Hacienda Business Park corporate campus anchor with affluent demographics.",
        city_id="san_francisco",
    ),
    "Dublin Downtown": SubmarketMeta(
        name="Dublin Downtown",
        borough="EAST_BAY",
        lat=37.7021,
        lng=-121.9358,
        zoom=14.0,
        pitch=40.0,
        base_lims=0.86,
        capex=8400000.0,
        permit_vel=50.0,
        shift_ratio=1.48,
        sla=56.0,
        description="Rapidly expanding Tri-Valley commercial core at the I-580/I-680 junction with modern master-planned residential communities.",
        city_id="san_francisco",
    ),
    "Livermore Downtown": SubmarketMeta(
        name="Livermore Downtown",
        borough="EAST_BAY",
        lat=37.6819,
        lng=-121.7680,
        zoom=14.0,
        pitch=40.0,
        base_lims=0.83,
        capex=7200000.0,
        permit_vel=41.0,
        shift_ratio=1.36,
        sla=50.0,
        description="Eastern Tri-Valley wine country and national laboratory (LLNL) technology anchor featuring a vibrant First Street cultural corridor.",
        city_id="san_francisco",
    ),

    # =======================================================================
    # PENINSULA (5 Submarkets)
    # =======================================================================
    "San Mateo Downtown": SubmarketMeta(
        name="San Mateo Downtown",
        borough="PENINSULA",
        lat=37.5630,
        lng=-122.3255,
        zoom=14.5,
        pitch=45.0,
        base_lims=0.86,
        capex=8600000.0,
        permit_vel=46.0,
        shift_ratio=1.42,
        sla=56.0,
        description="Vibrant Peninsula dining hub centered on 3rd and 4th avenues with Central Park, Caltrain station, and tech office infill.",
        city_id="san_francisco",
    ),
    "Burlingame Ave": SubmarketMeta(
        name="Burlingame Ave",
        borough="PENINSULA",
        lat=37.5779,
        lng=-122.3481,
        zoom=14.5,
        pitch=40.0,
        base_lims=0.88,
        capex=8400000.0,
        permit_vel=38.0,
        shift_ratio=1.34,
        sla=54.0,
        description="Upscale Peninsula retail and dining corridor known for tree-lined streetscapes, luxury boutiques, and affluent demographics.",
        city_id="san_francisco",
    ),
    "Redwood City Downtown": SubmarketMeta(
        name="Redwood City Downtown",
        borough="PENINSULA",
        lat=37.4852,
        lng=-122.2281,
        zoom=14.5,
        pitch=45.0,
        base_lims=0.87,
        capex=9500000.0,
        permit_vel=54.0,
        shift_ratio=1.54,
        sla=60.0,
        description="'Climate Best by Government Test' county seat experiencing significant downtown tech office expansion and transit-oriented housing.",
        city_id="san_francisco",
    ),
    "Menlo Park": SubmarketMeta(
        name="Menlo Park",
        borough="PENINSULA",
        lat=37.4538,
        lng=-122.1822,
        zoom=14.0,
        pitch=40.0,
        base_lims=0.91,
        capex=11200000.0,
        permit_vel=40.0,
        shift_ratio=1.45,
        sla=48.0,
        description="Venture capital capital on Sand Hill Road with Santa Cruz Avenue downtown retail and Meta global headquarters.",
        city_id="san_francisco",
    ),
    "South San Francisco": SubmarketMeta(
        name="South San Francisco",
        borough="PENINSULA",
        lat=37.6547,
        lng=-122.4077,
        zoom=14.0,
        pitch=45.0,
        base_lims=0.89,
        capex=12800000.0,
        permit_vel=62.0,
        shift_ratio=1.65,
        sla=50.0,
        description="'The Birthplace of Biotechnology' featuring the world's premier life sciences cluster around Oyster Point and Grand Avenue downtown.",
        city_id="san_francisco",
    ),
    "Daly City": SubmarketMeta(
        name="Daly City",
        borough="PENINSULA",
        lat=37.6879,
        lng=-122.4702,
        zoom=14.0,
        pitch=35.0,
        base_lims=0.81,
        capex=6800000.0,
        permit_vel=42.0,
        shift_ratio=1.30,
        sla=44.0,
        description="'Gateway to the Peninsula' with Westlake Shopping Center, major BART transit hub, and dense multi-family residential communities.",
        city_id="san_francisco",
    ),
    "San Bruno": SubmarketMeta(
        name="San Bruno",
        borough="PENINSULA",
        lat=37.6305,
        lng=-122.4111,
        zoom=14.0,
        pitch=40.0,
        base_lims=0.84,
        capex=7600000.0,
        permit_vel=46.0,
        shift_ratio=1.38,
        sla=48.0,
        description="YouTube global headquarters campus and San Mateo Avenue commercial district adjacent to SFO International Airport.",
        city_id="san_francisco",
    ),

    # =======================================================================
    # SILICON_VALLEY_SOUTH_BAY (6 Submarkets)
    # =======================================================================
    "Palo Alto University Ave": SubmarketMeta(
        name="Palo Alto University Ave",
        borough="SILICON_VALLEY_SOUTH_BAY",
        lat=37.4444,
        lng=-122.1609,
        zoom=14.5,
        pitch=45.0,
        base_lims=0.95,
        capex=13200000.0,
        permit_vel=42.0,
        shift_ratio=1.52,
        sla=62.0,
        description="Stanford University commercial anchor and global startup epicenter with prestigious University Avenue dining and tech office presence.",
        city_id="san_francisco",
    ),
    "Mountain View Castro St": SubmarketMeta(
        name="Mountain View Castro St",
        borough="SILICON_VALLEY_SOUTH_BAY",
        lat=37.3910,
        lng=-122.0808,
        zoom=14.5,
        pitch=45.0,
        base_lims=0.92,
        capex=11800000.0,
        permit_vel=50.0,
        shift_ratio=1.58,
        sla=66.0,
        description="Castro Street dining corridor and Caltrain/VTA transit hub anchored by Googleplex and surrounding tech innovation hubs.",
        city_id="san_francisco",
    ),
    "Sunnyvale Downtown": SubmarketMeta(
        name="Sunnyvale Downtown",
        borough="SILICON_VALLEY_SOUTH_BAY",
        lat=37.3770,
        lng=-122.0300,
        zoom=14.5,
        pitch=45.0,
        base_lims=0.89,
        capex=10500000.0,
        permit_vel=54.0,
        shift_ratio=1.50,
        sla=58.0,
        description="Historic Murphy Avenue and modern CityLine town center development in the heart of Silicon Valley defense and aerospace/tech corridor.",
        city_id="san_francisco",
    ),
    "Downtown San Jose": SubmarketMeta(
        name="Downtown San Jose",
        borough="SILICON_VALLEY_SOUTH_BAY",
        lat=37.3382,
        lng=-121.8863,
        zoom=14.5,
        pitch=55.0,
        base_lims=0.88,
        capex=11000000.0,
        permit_vel=59.0,
        shift_ratio=1.57,
        sla=68.0,
        description="Capital of Silicon Valley featuring San Pedro Square Market, Adobe headquarters towers, SAP Center, and major high-rise housing.",
        city_id="san_francisco",
    ),
    "Santana Row": SubmarketMeta(
        name="Santana Row",
        borough="SILICON_VALLEY_SOUTH_BAY",
        lat=37.3216,
        lng=-121.9478,
        zoom=15.0,
        pitch=50.0,
        base_lims=0.93,
        capex=12000000.0,
        permit_vel=48.0,
        shift_ratio=1.62,
        sla=75.0,
        description="Premier European-style luxury lifestyle district combining flagship luxury retail, fine dining, Class A creative office, and residential lofts.",
        city_id="san_francisco",
    ),
    "Cupertino": SubmarketMeta(
        name="Cupertino",
        borough="SILICON_VALLEY_SOUTH_BAY",
        lat=37.3230,
        lng=-122.0322,
        zoom=14.0,
        pitch=40.0,
        base_lims=0.91,
        capex=10800000.0,
        permit_vel=36.0,
        shift_ratio=1.40,
        sla=50.0,
        description="Global headquarters of Apple Inc. featuring Apple Park, Main Street Cupertino mixed-use core, and top-tier educational institutions.",
        city_id="san_francisco",
    ),
    "Santa Clara": SubmarketMeta(
        name="Santa Clara",
        borough="SILICON_VALLEY_SOUTH_BAY",
        lat=37.3541,
        lng=-121.9552,
        zoom=14.0,
        pitch=40.0,
        base_lims=0.90,
        capex=11400000.0,
        permit_vel=52.0,
        shift_ratio=1.52,
        sla=60.0,
        description="Silicon Valley technology powerhouse anchored by Intel headquarters, Nvidia campus, Santa Clara University, and Levi's Stadium corridor.",
        city_id="san_francisco",
    ),
    "North San Jose": SubmarketMeta(
        name="North San Jose",
        borough="SILICON_VALLEY_SOUTH_BAY",
        lat=37.3888,
        lng=-121.9214,
        zoom=14.0,
        pitch=45.0,
        base_lims=0.87,
        capex=10200000.0,
        permit_vel=55.0,
        shift_ratio=1.50,
        sla=58.0,
        description="Major technology innovation corridor along North First Street featuring Cisco headquarters, major R&D campuses, and VTA transit.",
        city_id="san_francisco",
    ),

    # =======================================================================
    # MARIN_NORTH_BAY (4 Submarkets)
    # =======================================================================
    "Sausalito": SubmarketMeta(
        name="Sausalito",
        borough="MARIN_NORTH_BAY",
        lat=37.8590,
        lng=-122.4853,
        zoom=14.0,
        pitch=45.0,
        base_lims=0.86,
        capex=7900000.0,
        permit_vel=28.0,
        shift_ratio=1.30,
        sla=65.0,
        description="Picturesque waterfront town across the Golden Gate with Bridgeway promenade shopping, ferry connectivity, and historic houseboat enclaves.",
        city_id="san_francisco",
    ),
    "Mill Valley": SubmarketMeta(
        name="Mill Valley",
        borough="MARIN_NORTH_BAY",
        lat=37.9060,
        lng=-122.5450,
        zoom=14.0,
        pitch=40.0,
        base_lims=0.87,
        capex=7500000.0,
        permit_vel=26.0,
        shift_ratio=1.26,
        sla=52.0,
        description="Redwood-canopied enclave at the base of Mount Tamalpais with historic downtown plaza, boutique retail, and outdoor recreation access.",
        city_id="san_francisco",
    ),
    "San Rafael Downtown": SubmarketMeta(
        name="San Rafael Downtown",
        borough="MARIN_NORTH_BAY",
        lat=37.9735,
        lng=-122.5311,
        zoom=14.0,
        pitch=40.0,
        base_lims=0.80,
        capex=6400000.0,
        permit_vel=39.0,
        shift_ratio=1.32,
        sla=48.0,
        description="Marin County's economic and transit center along Fourth Street with SMART rail station, cultural district, and bio/gaming development.",
        city_id="san_francisco",
    ),
    "Corte Madera": SubmarketMeta(
        name="Corte Madera",
        borough="MARIN_NORTH_BAY",
        lat=37.9256,
        lng=-122.5275,
        zoom=14.0,
        pitch=35.0,
        base_lims=0.82,
        capex=6600000.0,
        permit_vel=31.0,
        shift_ratio=1.28,
        sla=44.0,
        description="North Bay retail powerhouse featuring The Village at Corte Madera and Town Center shopping centers with marshland preservation.",
        city_id="san_francisco",
    ),
}

SF_SUBMARKETS = SAN_FRANCISCO_SUBMARKETS


# ---------------------------------------------------------------------------
# San Francisco Divisions Catalog
# ---------------------------------------------------------------------------

SAN_FRANCISCO_DIVISIONS: Dict[str, BoroughMeta] = {
    "SAN_FRANCISCO_CORE": BoroughMeta(
        name="SAN_FRANCISCO_CORE",
        center_lat=37.7749,
        center_lng=-122.4194,
        zoom=12.5,
        bbox=SF_DIVISION_BBOXES["SAN_FRANCISCO_CORE"],
        submarkets=[k for k, v in SAN_FRANCISCO_SUBMARKETS.items() if v.borough == "SAN_FRANCISCO_CORE"],
        city_id="san_francisco",
    ),
    "EAST_BAY": BoroughMeta(
        name="EAST_BAY",
        center_lat=37.8044,
        center_lng=-122.2711,
        zoom=12.0,
        bbox=SF_DIVISION_BBOXES["EAST_BAY"],
        submarkets=[k for k, v in SAN_FRANCISCO_SUBMARKETS.items() if v.borough == "EAST_BAY"],
        city_id="san_francisco",
    ),
    "PENINSULA": BoroughMeta(
        name="PENINSULA",
        center_lat=37.5485,
        center_lng=-122.3150,
        zoom=11.5,
        bbox=SF_DIVISION_BBOXES["PENINSULA"],
        submarkets=[k for k, v in SAN_FRANCISCO_SUBMARKETS.items() if v.borough == "PENINSULA"],
        city_id="san_francisco",
    ),
    "SILICON_VALLEY_SOUTH_BAY": BoroughMeta(
        name="SILICON_VALLEY_SOUTH_BAY",
        center_lat=37.3688,
        center_lng=-122.0363,
        zoom=11.5,
        bbox=SF_DIVISION_BBOXES["SILICON_VALLEY_SOUTH_BAY"],
        submarkets=[k for k, v in SAN_FRANCISCO_SUBMARKETS.items() if v.borough == "SILICON_VALLEY_SOUTH_BAY"],
        city_id="san_francisco",
    ),
    "MARIN_NORTH_BAY": BoroughMeta(
        name="MARIN_NORTH_BAY",
        center_lat=37.9150,
        center_lng=-122.5180,
        zoom=11.5,
        bbox=SF_DIVISION_BBOXES["MARIN_NORTH_BAY"],
        submarkets=[k for k, v in SAN_FRANCISCO_SUBMARKETS.items() if v.borough == "MARIN_NORTH_BAY"],
        city_id="san_francisco",
    ),
}

SF_DIVISIONS = SAN_FRANCISCO_DIVISIONS


from src.spatial.registration import SpatialRegistration

REGISTRATION = SpatialRegistration(
    metro_bbox=SAN_FRANCISCO_METRO_BBOX,
    division_bboxes=SAN_FRANCISCO_DIVISION_BBOXES,
    submarkets=SAN_FRANCISCO_SUBMARKETS,
    divisions=SAN_FRANCISCO_DIVISIONS,
    contains=is_in_sf_metro,
)
