apiVersion: v1
kind: Namespace
metadata:
  name: ingestion-producers
---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka-streaming
---
apiVersion: v1
kind: Namespace
metadata:
  name: stream-consumers
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-storage
---
apiVersion: v1
kind: Namespace
metadata:
  name: ml-inference
