"""Spatial indexing and graph topology modules."""

from src.spatial.cities.chicago import (
    CHICAGO_DIVISION_BBOXES,
    CHICAGO_DIVISIONS,
    CHICAGO_METRO_BBOX,
    CHICAGO_SUBMARKETS,
    is_in_chicago_metro,
)
from src.spatial.cities.san_francisco import (
    SAN_FRANCISCO_DIVISION_BBOXES,
    SAN_FRANCISCO_DIVISIONS,
    SAN_FRANCISCO_METRO_BBOX,
    SAN_FRANCISCO_SUBMARKETS,
    SF_DIVISION_BBOXES,
    SF_DIVISIONS,
    SF_METRO_BBOX,
    SF_SUBMARKETS,
    is_in_san_francisco_metro,
    is_in_sf_metro,
)
from src.spatial.geo_utils import (
    NYC_BOROUGH_BBOXES,
    NYC_METRO_BBOX,
    create_shapely_polygon,
    get_borough_for_coordinate,
    get_borough_for_h3,
    get_city_for_coordinate,
    get_division_for_coordinate,
    get_division_for_h3,
    h3_boundary_to_polygon_wkt,
    is_in_nyc_metro,
    point_to_postgis_sql,
    point_to_wkt,
)
from src.spatial.graph_builder import H3HexGraphBuilder
from src.spatial.h3_indexer import H3SpatialIndexer
from src.spatial.submarkets import (
    NYC_BOROUGHS,
    NYC_SUBMARKETS,
    BoroughMeta,
    DivisionMeta,
    SubmarketMeta,
    find_nearest_submarket,
    get_all_submarkets,
    get_borough_catalog,
    get_city_catalog,
    get_division_catalog,
    get_submarket_by_name,
    get_submarkets,
)

__all__ = [
    "H3SpatialIndexer",
    "H3HexGraphBuilder",
    "NYC_BOROUGH_BBOXES",
    "NYC_METRO_BBOX",
    "CHICAGO_METRO_BBOX",
    "CHICAGO_DIVISION_BBOXES",
    "CHICAGO_DIVISIONS",
    "CHICAGO_SUBMARKETS",
    "SF_METRO_BBOX",
    "SAN_FRANCISCO_METRO_BBOX",
    "SF_DIVISION_BBOXES",
    "SAN_FRANCISCO_DIVISION_BBOXES",
    "SF_DIVISIONS",
    "SAN_FRANCISCO_DIVISIONS",
    "SF_SUBMARKETS",
    "SAN_FRANCISCO_SUBMARKETS",
    "is_in_nyc_metro",
    "is_in_chicago_metro",
    "is_in_sf_metro",
    "is_in_san_francisco_metro",
    "get_city_for_coordinate",
    "point_to_wkt",
    "point_to_postgis_sql",
    "h3_boundary_to_polygon_wkt",
    "create_shapely_polygon",
    "get_borough_for_coordinate",
    "get_borough_for_h3",
    "get_division_for_coordinate",
    "get_division_for_h3",
    "SubmarketMeta",
    "BoroughMeta",
    "DivisionMeta",
    "NYC_SUBMARKETS",
    "NYC_BOROUGHS",
    "get_all_submarkets",
    "get_submarkets",
    "get_submarket_by_name",
    "find_nearest_submarket",
    "get_borough_catalog",
    "get_city_catalog",
    "get_division_catalog",
]
